spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/oauth2_user_convert_to_entity
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          GOOGLE:
            clientId: 1059223748202-g5t4ts5vboaf044vaohhf3m726qf72ok.apps.googleusercontent.com
            clientSecret: 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
          FACEBOOK:
            clientId: 862672541509555
            clientSecret: 2cfa304cd4f11d1b2b7d3eb000d59132
          GITHUB:
            clientId: c5072f2e5794c37e80de
            clientSecret: d4eb9d4ce91ee652f0c2eae777a986aef450a4b9
  thymeleaf:
    cache: false